/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterContractSol from "./CounterContract.sol";
export { TrustlessVoting__factory } from "./TrustlessVoting__factory";
